In [154]:
import pandas as pd

In [155]:
from sqlalchemy import create_engine

In [126]:
df = pd.read_csv('/Users/lilianmaina/Desktop/DataEngineeringProject/wfp_food_prices_ken.csv')

In [127]:
df.shape

(17632, 16)

In [156]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17632 entries, 0 to 17631
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          17632 non-null  str
 1   admin1        17585 non-null  str
 2   admin2        17585 non-null  str
 3   market        17632 non-null  str
 4   market_id     17632 non-null  int64
 5   latitude      17585 non-null  float64
 6   longitude     17585 non-null  float64
 7   category      17632 non-null  str
 8   commodity     17632 non-null  str
 9   commodity_id  17632 non-null  int64
 10  unit          17632 non-null  str
 11  priceflag     17632 non-null  str
 12  pricetype     17632 non-null  str
 13  currency      17632 non-null  str
 14  price         17632 non-null  float64
 15  usdprice      17632 non-null  float64
dtypes: float64(4), int64(2), str(10)
memory usage: 2.2 MB

In [157]:
df.columns

Index(['date', 'admin1', 'admin2', 'market', 'market_id', 'latitude',
       'longitude', 'category', 'commodity', 'commodity_id', 'unit',
       'priceflag', 'pricetype', 'currency', 'price', 'usdprice'],
      dtype='str')

In [128]:
df.head()

,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,unit,priceflag,pricetype,currency,price,usdprice
0,2006-01-15,Coast,Mombasa,Mombasa,191,-4.05,39.67,cereals and tubers,Maize,51,KG,actual,Wholesale,KES,16.13,0.22
1,2006-01-15,Coast,Mombasa,Mombasa,191,-4.05,39.67,pulses and nuts,Beans,50,KG,actual,Wholesale,KES,33.63,0.47
2,2006-01-15,Eastern,Marsabit,Marsabit,190,2.33,37.98,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,21.00,0.29
3,2006-01-15,Nairobi,Nairobi,Nairobi,184,-1.28,36.82,cereals and tubers,Bread,55,400 G,actual,Retail,KES,26.00,0.36
4,2006-01-15,Nairobi,Nairobi,Nairobi,184,-1.28,36.82,cereals and tubers,Maize,51,KG,actual,Wholesale,KES,15.48,0.22

In [130]:
engine = create_engine('mysql+pymysql://root:Hahaha!1!@localhost:3306/food_prices_ken')

In [131]:
df.to_sql(
  name = 'raw_food_prices',
  con = engine,
  if_exists = 'append',
  index = False
)
print('Successfully added and loaded to food_prices_ken db')

Successfully added and loaded to food_prices_ken db

In [132]:
sql_query = """
SELECT date, market, commodity, unit, price, currency
FROM raw_food_prices
WHERE admin1 = 'Nairobi'
ORDER BY date DESC
LIMIT 20; """

In [133]:
df_all = pd.read_sql(sql_query, con=engine)
df_all

         date             market           commodity   unit    price currency
0  2025-10-15  Kangemi (Nairobi)    Beans (dolichos)  90 KG   5700.0      KES
1  2025-10-15  Kangemi (Nairobi)    Beans (dolichos)  90 KG   5700.0      KES
2  2025-10-15  Kangemi (Nairobi)    Beans (rosecoco)  90 KG  10300.0      KES
3  2025-10-15  Kangemi (Nairobi)    Beans (dolichos)  90 KG   5700.0      KES
4  2025-10-15  Kangemi (Nairobi)            Tomatoes  64 KG   2880.0      KES
5  2025-10-15  Kangemi (Nairobi)            Tomatoes  64 KG   2880.0      KES
6  2025-10-15  Kangemi (Nairobi)            Tomatoes  64 KG   2880.0      KES
7  2025-10-15  Kangemi (Nairobi)    Beans (rosecoco)  90 KG  10300.0      KES
8  2025-10-15  Kangemi (Nairobi)    Beans (rosecoco)  90 KG  10300.0      KES
9  2025-10-15  Kangemi (Nairobi)    Beans (dolichos)  90 KG   5700.0      KES
10 2025-10-15  Kangemi (Nairobi)            Tomatoes  64 KG   2880.0      KES
11 2025-10-15  Kangemi (Nairobi)    Beans (rosecoco)  90 KG  10300.0      KES
12 2025-10-15  Kangemi (Nairobi)    Beans (dolichos)  90 KG   5700.0      KES
13 2025-10-15  Kangemi (Nairobi)    Beans (dolichos)  90 KG   5700.0      KES
14 2025-10-15  Kangemi (Nairobi)    Beans (rosecoco)  90 KG  10300.0      KES
15 2025-10-15  Kangemi (Nairobi)            Tomatoes  64 KG   2880.0      KES
16 2025-10-15  Kangemi (Nairobi)    Beans (rosecoco)  90 KG  10300.0      KES
17 2025-10-15  Kangemi (Nairobi)            Tomatoes  64 KG   2880.0      KES
18 2025-08-15  Kangemi (Nairobi)  Maize (white, dry)  90 KG   4400.1      KES
19 2025-08-15  Kangemi (Nairobi)  Maize (white, dry)  90 KG   4400.1      KES

In [134]:
sql_query = """
SELECT commodity, 
	ROUND(AVG(price), 2) AS avg_price,
    MIN(price) AS min_price,
    MAX(price) AS max_price,
    COUNT(*) AS total_records
FROM raw_food_prices
GROUP BY commodity
ORDER BY avg_price DESC; """

In [135]:
df_all = pd.read_sql(sql_query, con=engine)
df_all

                     commodity  avg_price  min_price  max_price  total_records
0               Beans (yellow)   10706.14    5400.00   18252.00           1602
1             Beans (dolichos)   10191.44    1500.00   17100.00            960
2                 Beans (mung)    9895.15    7200.00   12270.00            198
3             Beans (rosecoco)    9440.35    5850.00   19800.00            996
4                      Cowpeas    8604.62    2100.42   16200.00            960
5               Beans (kidney)    7490.53    1134.00   14850.00            474
6              Millet (finger)    7396.64    3600.00   11997.00            270
7              Sorghum (white)    5900.84    2700.00    8700.00            486
8    Rice (imported, Pakistan)    4931.47    3917.00    6305.00             90
9                Sorghum (red)    4847.07    3240.00    7200.00            306
10                    Tomatoes    3776.23     426.88   10628.48           2010
11                     Cabbage    3204.52      27.46   11970.00           1914
12     Potatoes (Irish, white)    2486.15     751.00    6120.00           1668
13                     Sorghum    2458.58      30.00    7470.00           4188
14                 Beans (dry)    2415.99      23.00   10000.00           6648
15       Potatoes (Irish, red)    2346.65     868.00    5310.00            762
16          Maize (white, dry)    2055.00      33.00    8128.00           3498
17             Rice (aromatic)    1986.30      87.00   10000.00           3630
18               Maize (white)    1104.95       8.00    4898.00           7296
19            Potatoes (Irish)    1061.69      35.00    5700.00           5484
20                        Kale     918.45       5.00    5000.00           3132
21                Onions (dry)     913.57     390.00    8100.00           2010
22                 Meat (goat)     615.20     400.00     881.25           1368
23                Meat (camel)     532.31     400.00     700.00            888
24                 Meat (beef)     531.91      10.00     800.00           1404
25  Oil (vegetable, fortified)     292.05     120.00     403.00           2748
26             Oil (vegetable)     238.66     115.00     400.00           3372
27           Pigeon peas (dry)     214.59     100.00     700.00            396
28                 Cooking fat     188.13     120.00     380.00            534
29               Cowpeas (dry)     163.63      50.00     310.00            900
30                       Sugar     158.67      90.36     305.00           5310
31           Fish (omena, dry)     156.69     130.00     198.00             78
32         Milk (camel, fresh)     136.08      50.00     280.00            426
33           Milk (cow, fresh)     123.96      60.00     203.89             96
34                        Rice     121.56      78.33     220.00           2124
35     Milk (cow, pasteurized)     121.01      20.00     280.00           2826
36                       Beans     105.66      28.23     270.00           6114
37      Fuel (petrol-gasoline)     102.12      83.33     118.11            264
38                 Wheat flour      98.69      50.00     174.00           4782
39         Maize flour (white)      96.13      46.00     195.00           2988
40               Fuel (diesel)      90.41      65.70     109.72            258
41                 Maize flour      81.30      50.00     137.80           2682
42                     Spinach      79.19      14.00     260.00           1104
43             Fuel (kerosene)      77.80      39.62     111.83            210
44                  Milk (UHT)      70.38      27.00     100.45           2472
45                       Bread      40.18      26.00      50.00            636
46                       Maize      39.29      10.43     120.00           6216
47               Cowpea leaves      32.02      10.00      87.00            162
48                     Bananas      14.19       5.00      21.67           2016
49                        Salt      12.19       8.24      55.00           4836

In [136]:
sql_query = """
SELECT commodity, COUNT(DISTINCT market) AS market_count -- REVIEW WITHOUT DISTINCT
FROM raw_food_prices
GROUP BY commodity
HAVING market_count > 10
ORDER BY market_count DESC;
"""

In [137]:
df_all = pd.read_sql(sql_query, con=engine)
df_all

                     commodity  market_count
0                        Sugar           186
1              Rice (aromatic)           181
2                  Wheat flour           176
3                         Salt           173
4                        Beans           172
5          Maize flour (white)           170
6   Oil (vegetable, fortified)           161
7           Maize (white, dry)           155
8      Milk (cow, pasteurized)           153
9                         Kale           125
10                     Spinach            97
11               Cowpeas (dry)            85
12           Pigeon peas (dry)            48
13                 Beans (dry)            40
14            Potatoes (Irish)            37
15                     Cabbage            35
16                       Maize            35
17                 Maize flour            32
18                     Bananas            32
19                  Milk (UHT)            32
20                        Rice            32
21             Oil (vegetable)            31
22                     Sorghum            31
23                 Meat (beef)            28
24                 Meat (goat)            23
25                 Cooking fat            23
26                Onions (dry)            21
27                    Tomatoes            21
28              Beans (yellow)            19
29         Milk (camel, fresh)            19
30                Meat (camel)            17
31                     Cowpeas            17
32       Potatoes (Irish, red)            17
33     Potatoes (Irish, white)            17
34            Beans (rosecoco)            17
35              Beans (kidney)            17
36            Beans (dolichos)            16
37               Maize (white)            14
38               Sorghum (red)            14
39             Sorghum (white)            13
40             Millet (finger)            12
41                Beans (mung)            12
42           Milk (cow, fresh)            11

In [138]:
sql_query = """
SELECT admin2, EXTRACT(YEAR FROM date) AS year, ROUND(AVG(price), 2) as avg_price
FROM raw_food_prices
GROUP BY admin2, year
ORDER BY admin2, year;
"""

In [139]:
df_all = pd.read_sql(sql_query, con=engine)
df_all

         admin2  year  avg_price
0           NaN  2015      38.50
1           NaN  2016      46.75
2           NaN  2017      60.76
3           NaN  2018      53.41
4           NaN  2019      56.26
..          ...   ...        ...
253       Wajir  2024     139.33
254       Wajir  2025     146.33
255  West Pokot  2021    4595.51
256  West Pokot  2022    4399.39
257  West Pokot  2023    5198.17

[258 rows x 3 columns]

In [140]:
sql_query = """
SELECT date, admin2, market, commodity, price
FROM raw_food_prices
WHERE date >= '2025-01-01'
ORDER BY date DESC;
"""

In [141]:
df_all = pd.read_sql(sql_query, con=engine)
df_all

           date   admin2                 market         commodity   price
0    2025-11-15  Garissa     Dagahaley (Daadab)       Maize flour   99.22
1    2025-11-15  Garissa     Dagahaley (Daadab)  Potatoes (Irish)   60.16
2    2025-11-15  Garissa     Dagahaley (Daadab)       Wheat flour   99.65
3    2025-11-15  Garissa     Dagahaley (Daadab)       Meat (goat)  881.25
4    2025-11-15  Garissa     Dagahaley (Daadab)        Milk (UHT)   52.23
...         ...      ...                    ...               ...     ...
8815 2025-01-15  Turkana  Kalobeyei (Village 3)        Milk (UHT)   77.50
8816 2025-01-15  Turkana  Kalobeyei (Village 3)              Salt   10.00
8817 2025-01-15  Turkana  Kalobeyei (Village 3)             Sugar  165.00
8818 2025-01-15  Turkana  Kalobeyei (Village 3)       Beans (dry)  130.00
8819 2025-01-15  Turkana  Kalobeyei (Village 3)           Bananas   20.00

[8820 rows x 5 columns]

In [142]:
sql_query = """
SELECT commodity, pricetype, ROUND(AVG(price), 2) AS avg_price, COUNT(*) AS records
FROM raw_food_prices
GROUP BY commodity, pricetype
ORDER BY commodity, pricetype
"""

In [143]:
df_all = pd.read_sql(sql_query, con=engine)
df_all

           commodity  pricetype  avg_price  records
0            Bananas     Retail      14.19     2016
1              Beans     Retail     159.68     2778
2              Beans  Wholesale      60.68     3336
3   Beans (dolichos)  Wholesale   10191.44      960
4        Beans (dry)     Retail     113.91     3984
..               ...        ...        ...      ...
56           Spinach     Retail      92.14      876
57           Spinach  Wholesale      29.42      228
58             Sugar     Retail     158.67     5310
59          Tomatoes  Wholesale    3776.23     2010
60       Wheat flour     Retail      98.69     4782

[61 rows x 4 columns]